-------------------------------------------------------------------------------
-- |
-- Module      : Absol.Metaspec.Special
-- Description : Support functions for the metaspec language features. 
-- Copyright   : (c) Ara Adkins (2017)
-- License     : See LICENSE file
--
-- Maintainer  : Ara Adkins
-- Stability   : experimental
-- Portability : GHC
--
-- A module providing metacompiler-level support for the language special 
-- features. 
--
-------------------------------------------------------------------------------
module Absol.Metaspec.Special where
