-------------------------------------------------------------------------------
-- |
-- Module      : Absol.Metaspec
-- Description : Functions for handling metaspec-specific language features.
-- Copyright   : (c) Ara Adkins (2017)
-- License     : See LICENSE file
--
-- Maintainer  : Ara Adkins
-- Stability   : experimental
-- Portability : GHC
--
-- A module for working with metaspec language features.
--
-------------------------------------------------------------------------------
module Absol.Metaspec where
