-------------------------------------------------------------------------------
-- |
-- Module      : Absol.Metagen
-- Description : The implementation of the ABSOL code generation engine.
-- Copyright   : (c) Ara Adkins (2017)
-- License     : See LICENSE file
-- 
-- Maintainer  : Ara Adkins
-- Stability   : experimental
-- Portability : GHC
-- 
-- Functionality for generating the target compiler code. This file is currently
-- empty as code generation has been put out of scope of the project. It remains
-- as a point for future extension. 
--
-------------------------------------------------------------------------------
module Absol.Metagen where
